questions = {
    "topic_search": [
        "What courses cover deep learning?",
        "What courses are about natural language processing?",
        "Which courses involve machine learning?",
        "What courses deal with databases?",
        "Are there any courses on robotics?",
        "What courses involve signal processing?",
        "What courses cover bioinformatics?",
        "Which courses are about cloud computing?",
    ],
    "program_requirements": [
        "What are the requirements for MS in Computer Science?",
        "What courses are needed for PhD in Biomedical Engineering?",
        "What is the curriculum for Master of Architecture?",
        "What courses are required for MS in Data Science?",
        "What is the Master of Cybersecurity curriculum?",
        "What are the core courses for MBA?",
        "What degrees does the department offer?",
        "What is the course structure for MS in Finance?",
    ],
    "policy": [
        "What is the thesis requirement for MS programs?",
        "What is the policy for incomplete grades?",
        "How does the co-terminal degree program work?",
        "What is the time limit to complete a PhD?",
        "What is the policy for repeating courses?",
        "What are the residency requirements for PhD?",
        "What is the qualifying exam requirement?",
        "How does academic dismissal work?",
        "What is the grading policy for graduate students?",
    ],
    "admission": [
        "What are the GPA requirements for graduate admission?",
        "What is the GRE waiver policy?",
        "What are the TOEFL requirements for international students?",
        "Are letters of recommendation required?",
        "What documents are required for graduate application?",
        "What GRE scores are needed for admission?",
        "What is the minimum GPA for PhD admission?",
        "What is the English proficiency requirement?",
    ],
    "financial": [
        "What scholarships are available for graduate students?",
        "How much does a graduate credit hour cost?",
        "What financial aid is available?",
        "How does tuition waiver work?",
        "Are there fellowships available for PhD students?",
        "What is the graduate assistantship policy?",
        "What is the tuition deferment plan?",
    ],
}